main: net.hauc3.hauc3raft.plus.HauC3raft
version: 1.0
name: HauC3raft-Plus-Edition-Because-I-Lost-The-Code-To-The-Old-Version-Somehow-Also-This-Plugin-Requires-The-Old-Version-To-Be-Installed
api-version: 1.20
depend: [MapEngine, MapMediaExt, LuckPerms, PremiumVanish, ProtocolLib, PlasmoVoice, HauC3raft]